codecov:
  require_ci_to_pass: true
  max_report_age: false
coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: git_json
      name: git_json
      paths:
        - "git_json/**"